### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by NORXONDOR** [StiliyanKushev/csgo-tradeup-cli#12] opened 2023-03-25 21:56 UTC
This application needs better documentation. Either that, or its completely broken, because everything I try does not seem to work for its intended purpose.

**Comment by StiliyanKushev** [comment] 2023-03-26 00:43
Hello there. I am the author of this repo. This project is mostly abandoned, however I may consider writing some examples, as I have used it in the past, and even recently. Furthermore, if you have any issues, you should provide a step by step guide on how to reproduce them, and I will fix them in my free time.

**Comment by StiliyanKushev** [comment] 2023-03-26 01:43
Hello. I'm happy to report that after I tested the program myself for about an hour, I was unable to notice any abnormal behavior. Everything seems to be functional, apart from some small issues that are now fixed. Please note, that there's currently no documentation, and no plans to write such. Luckily, the help menu describes the program's capabilities considerably well enough as it is.

That being said, if you experience any issues, please report them with a step by step guide on how to reproduce them. I'd be happy to help :)

**Closed** 2023-03-26 10:58 UTC
