### ISSUE TITLE
No skins can be found with the passed parameters! Aborting...

### ISSUE THREAD

**Issue by iAnvar** [StiliyanKushev/csgo-tradeup-cli#19] opened 2024-02-17 09:56 UTC
1) git clone https://github.com/StiliyanKushev/csgo-tradeup-cli.git

<img width="1106" alt="Снимок экрана 2024-02-17 в 14 36 56" src="https://github.com/StiliyanKushev/csgo-tradeup-cli/assets/84909834/6d257ffe-502f-4483-a794-937de48cf32d">

2) go to the folder of the project and run "npm i"

<img width="854" alt="Снимок экрана 2024-02-17 в 14 48 09" src="https://github.com/StiliyanKushev/csgo-tradeup-cli/assets/84909834/899ee26d-4736-4f13-a840-5a3e3a29abbf">

3) used command npm audit fix

<img width="783" alt="Снимок экрана 2024-02-17 в 14 49 52" src="https://github.com/StiliyanKushev/csgo-tradeup-cli/assets/84909834/b3dc7a21-eb38-4910-b45d-7cef96d7ccd8">

4) run project with parameters - node index --profit 110 --spy --visualize

<img width="882" alt="Снимок экрана 2024-02-17 в 14 52 04" src="https://github.com/StiliyanKushev/csgo-tradeup-cli/assets/84909834/74a832a0-5247-4d7e-81e4-e452f22f29f9">

5) got error

<img width="867" alt="Снимок экрана 2024-02-17 в 14 54 50" src="https://github.com/StiliyanKushev/csgo-tradeup-cli/assets/84909834/3e67b063-b320-47a5-a903-5ecaf13fd6b4">

**Comment by iAnvar** [comment] 2024-02-17 11:27
<img width="784" alt="Снимок экрана 2024-02-17 в 16 26 55" src="https://github.com/StiliyanKushev/csgo-tradeup-cli/assets/84909834/59bce7cd-fd5c-43f0-8644-b4ae80300032">

**Comment by StiliyanKushev** [comment] 2024-06-04 10:40
Cannot reproduce, closing.

**Closed as completed by StiliyanKushev** 2024-06-04 10:40 UTC
